 export const GridMeta = [
  { id: 'ENG001', codename: 'Tesla', class: 'infrastructure', strategy: 'stack', description: 'Sentiment delta parser' },
  { id: 'ENG002', codename: 'Magnum', class: 'infrastructure', strategy: 'converge', description: 'Reversal timing scanner' },
  { id: 'ENG003', codename: 'Helix', class: 'infrastructure', strategy: 'index', description: 'Echo pattern amplifier' },
  { id: 'ENG004', codename: 'Overdrive', class: 'behavioral', strategy: 'neutralize', description: 'Volume aggression filter' },
  { id: 'ENG005', codename: 'Recoil', class: 'strategic', strategy: 'momentum', description: 'Behavioral trap identifier' },
  { id: 'ENG006', codename: 'Echo', class: 'infrastructure', strategy: 'stack', description: 'Reversal timing scanner' },
  { id: 'ENG007', codename: 'Virus', class: 'expansion', strategy: 'pattern', description: 'Autonomous signal combiner' },
  { id: 'ENG008', codename: 'Synapse', class: 'behavioral', strategy: 'feedback', description: 'Pulse null smooth' },
  { id: 'ENG009', codename: 'Impulse', class: 'tactical', strategy: 'fallback', description: 'Confluence scanner engine' },
  { id: 'ENG010', codename: 'EchoChase', class: 'tactical', strategy: 'echo', description: 'Stack-level spoof logic' },

  { id: 'ENG011', codename: 'Capitula', class: 'behavioral', strategy: 'quantity', description: 'Grid loop activator' },
  { id: 'ENG012', codename: 'Doubt', class: 'strategic', strategy: 'loop', description: 'Volume aggression filter' },
  { id: 'ENG013', codename: 'Drain', class: 'behavioral', strategy: 'detection', description: 'Behavioral trap identifier' },
  { id: 'ENG014', codename: 'Swarm', class: 'infrastructure', strategy: 'feedback', description: 'Echo pattern amplifier' },
  { id: 'ENG015', codename: 'Comet', class: 'behavioral', strategy: 'neutralize', description: 'Grid loop activator' },
  { id: 'ENG016', codename: 'FalseLead', class: 'strategic', strategy: 'volume', description: 'Behavioral trap identifier' },
  { id: 'ENG017', codename: 'Loop', class: 'strategic', strategy: 'echo', description: 'Quant timing assistant' },
  { id: 'ENG018', codename: 'Snapback', class: 'behavioral', strategy: 'volume', description: 'Fallback executor core' },
  { id: 'ENG019', codename: 'Pulse', class: 'control', strategy: 'stack', description: 'Price match locator' },
  { id: 'ENG020', codename: 'Forge', class: 'strategic', strategy: 'momentum', description: 'Autonomous signal combiner' },

  { id: 'ENG021', codename: 'Core', class: 'tactical', strategy: 'detection', description: 'Behavioral trap identifier' },
  { id: 'ENG022', codename: 'Reservoir', class: 'infrastructure', strategy: 'stack', description: 'Stack-level spoof logic' },
  { id: 'ENG023', codename: 'Yieldcraft', class: 'control', strategy: 'fallback', description: 'Fallback executor core' },
  { id: 'ENG024', codename: 'Indexor', class: 'tactical', strategy: 'reactive', description: 'Quant timing assistant' },
  { id: 'ENG025', codename: 'BeaconFund', class: 'behavioral', strategy: 'volume', description: 'Volume aggression filter' },
  { id: 'ENG026', codename: 'Anchor', class: 'infrastructure', strategy: 'proxy', description: 'Autonomous signal combiner' },
  { id: 'ENG027', codename: 'Horizon', class: 'control', strategy: 'momentum', description: 'Fallback executor core' },
  { id: 'ENG028', codename: 'Nest', class: 'expansion', strategy: 'neutralize', description: 'Sentiment delta parser' },
  { id: 'ENG029', codename: 'MomentumHold', class: 'strategic', strategy: 'neutralize', description: 'Sentiment delta parser' },
  { id: 'ENG030', codename: 'Equinox', class: 'control', strategy: 'reactive', description: 'Smart liquidity flagger' },

  { id: 'ENG031', codename: 'Epoch', class: 'tactical', strategy: 'grid', description: 'Echo pattern amplifier' },
  { id: 'ENG032', codename: 'Trackline', class: 'strategic', strategy: 'echo', description: 'Grid loop activator' },
  { id: 'ENG033', codename: 'Lodestar', class: 'behavioral', strategy: 'stack', description: 'Autonomous signal combiner' },
  { id: 'ENG034', codename: 'Harvest', class: 'strategic', strategy: 'quantity', description: 'Volume aggression filter' },
  { id: 'ENG035', codename: 'Organism', class: 'control', strategy: 'momentum', description: 'Fallback executor core' },
  { id: 'ENG036', codename: 'Genome', class: 'tactical', strategy: 'reactive', description: 'Grid loop activator' },
  { id: 'ENG037', codename: 'Redshift', class: 'expansion', strategy: 'momentum', description: 'Volume spoof combiner' },
  { id: 'ENG038', codename: 'Zenith', class: 'strategic', strategy: 'reactive', description: 'Grid loop activator' },
  { id: 'ENG039', codename: 'Orbit', class: 'tactical', strategy: 'grid', description: 'Stack-level spoof logic' },
  { id: 'ENG040', codename: 'Bridge', class: 'expansion', strategy: 'pattern', description: 'Fallback executor core' },

  { id: 'ENG041', codename: 'Vector', class: 'expansion', strategy: 'loop', description: 'Smart liquidity flagger' },
  { id: 'ENG042', codename: 'Scanner', class: 'expansion', strategy: 'momentum', description: 'Volume aggression filter' },
  { id: 'ENG043', codename: 'Mosaic', class: 'expansion', strategy: 'neutralize', description: 'Volume spoof logic' },
  { id: 'ENG044', codename: 'OrbitX', class: 'expansion', strategy: 'feedback', description: 'Autonomous signal combiner' },
  { id: 'ENG045', codename: 'Cryo', class: 'infrastructure', strategy: 'volume', description: 'Echo pattern amplifier' },
  { id: 'ENG046', codename: 'Atmos', class: 'infrastructure', strategy: 'volume', description: 'Echo pattern amplifier' },
  { id: 'ENG047', codename: 'Neuronet', class: 'strategic', strategy: 'fallback', description: 'Sentiment delta parser' },
  { id: 'ENG048', codename: 'Warden', class: 'behavioral', strategy: 'neutralize', description: 'Stack-level spoof logic' },
  { id: 'ENG049', codename: 'Chronicle', class: 'expansion', strategy: 'echo', description: 'Autonomous signal combiner' },
  { id: 'ENG050', codename: 'Relay', class: 'control', strategy: 'converge', description: 'Stack-level spoof logic' },

  { id: 'ENG051', codename: 'Clarity', class: 'expansion', strategy: 'quantity', description: 'Smart liquidity flagger' },
  { id: 'ENG052', codename: 'Beacon', class: 'strategic', strategy: 'neutralize', description: 'Fallback executor core' },
  { id: 'ENG053', codename: 'Callsign', class: 'strategic', strategy: 'loop', description: 'Behavioral trap identifier' },
  { id: 'ENG054', codename: 'Coach', class: 'infrastructure', strategy: 'loop', description: 'Volume aggression filter' },
  { id: 'ENG055', codename: 'Finale', class: 'tactical', strategy: 'detection', description: 'Fallback executor core' },
  { id: 'ENG056', codename: 'Hibernus', class: 'behavioral', strategy: 'bias', description: 'Stack-level spoof logic' },
  { id: 'ENG057', codename: 'Refinery', class: 'behavioral', strategy: 'pattern', description: 'Fallback executor core' },
  { id: 'ENG058', codename: 'Spectra', class: 'control', strategy: 'stack', description: 'Stack-level spoof logic' },
  { id: 'ENG059', codename: 'Vector2', class: 'control', strategy: 'momentum', description: 'Fallback executor core' },
  { id: 'ENG060', codename: 'Schematic', class: 'strategic', strategy: 'neutralize', description: 'Volume aggression filter' },

  { id: 'ENG061', codename: 'PrimeGrid', class: 'strategic', strategy: 'echo', description: 'Quant timing assistant' },
  { id: 'ENG062', codename: 'PulseNet', class: 'strategic', strategy: 'pattern', description: 'Volume spoof logic' },
  { id: 'ENG063', codename: 'CorePrime', class: 'infrastructure', strategy: 'detection', description: 'Autonomous signal combiner' },
  { id: 'ENG064', codename: 'Override', class: 'strategic', strategy: 'proxy', description: 'Fallback executor core' },
  { id: 'ENG065', codename: 'FinalCore', class: 'control', strategy: 'pattern', description: 'Smart liquidity flagger' },
  { id: 'ENG066', codename: 'SimTrain', class: 'expansion', strategy: 'stack', description: 'Confluence scanner engine' },
  { id: 'ENG067', codename: 'Observer', class: 'infrastructure', strategy: 'proxy', description: 'Sentiment delta parser' },
];