import jsPDF from 'jspdf';

export async function generateAgentPDF(agent: {
  id: string;
  name: string;
  role: string;
  status: string;
  lastSeen: string;
  logs: { timestamp: string; action: string }[];
}) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(16);
  doc.text(`EchoMind Agent Report`, 14, 20);

  // Agent Info
  doc.setFontSize(12);
  doc.text(`Name: ${agent.name}`, 14, 30);
  doc.text(`ID: ${agent.id}`, 14, 36);
  doc.text(`Role: ${agent.role}`, 14, 42);
  doc.text(`Status: ${agent.status}`, 14, 48);
  doc.text(`Last Seen: ${agent.lastSeen}`, 14, 54);

  // Section Title
  doc.setFontSize(14);
  doc.text(`Recent Actions`, 14, 66);
  doc.setFontSize(10);
  doc.setDrawColor(0);
  doc.setLineWidth(0.1);

  // Logs
  const logs = agent.logs.slice(0, 25); // limit to 25 logs
  let y = 72;
  logs.forEach((log, i) => {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(`${log.timestamp} — ${log.action}`, 14, y);
    y += 6;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`Generated by EchoMind`, 14, 290);

  // Save
  doc.save(`agent-${agent.id}-report.pdf`);
}