import jsPDF from 'jspdf';

export async function generateUserPDF(user: {
  id: string;
  alias: string;
  role: string;
  xp: number;
  locked_xp?: number;
  echomindScore?: number;
  logs: { timestamp: string; xp: number; reason: string }[];
  redemptions: { timestamp: string; redeemed_xp: number; payout_status?: string }[];
  referrals: { timestamp: string; referrer_email: string; referred_email: string }[];
}) {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text('Felena Theory Operator Audit Report', 14, 20);
  doc.setFontSize(12);
  doc.text(`Alias: ${user.alias}`, 14, 30);
  doc.text(`User ID: ${user.id}`, 14, 36);
  doc.text(`Role: ${user.role}`, 14, 42);
  doc.text(`XP: ${user.xp}`, 14, 48);
  doc.text(`Locked XP: ${user.locked_xp || 0}`, 14, 54);
  doc.text(`EchoMind Score: ${user.echomindScore ?? 'N/A'}`, 14, 60);

  doc.setFontSize(14);
  doc.text('XP Log', 14, 72);
  doc.setFontSize(10);
  let y = 78;
  user.logs.slice(0, 20).forEach(log => {
    if (y > 280) { doc.addPage(); y = 20; }
    doc.text(`${log.timestamp} — +${log.xp} XP — ${log.reason}`, 14, y);
    y += 6;
  });

  doc.setFontSize(14);
  doc.text('Redemptions', 14, y + 10);
  y += 16;
  doc.setFontSize(10);
  user.redemptions.slice(0, 15).forEach(r => {
    if (y > 280) { doc.addPage(); y = 20; }
    doc.text(`${r.timestamp} — ${r.redeemed_xp} XP — Status: ${r.payout_status || 'pending'}`, 14, y);
    y += 6;
  });

  doc.setFontSize(14);
  doc.text('Referrals', 14, y + 10);
  y += 16;
  doc.setFontSize(10);
  user.referrals.slice(0, 10).forEach(ref => {
    if (y > 280) { doc.addPage(); y = 20; }
    doc.text(`${ref.timestamp} — ${ref.referrer_email} → ${ref.referred_email}`, 14, y);
    y += 6;
  });

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`Generated by EchoMind`, 14, 290);
  doc.save(`user-${user.id}-audit.pdf`);
}